config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "dashboards", to: "dashboards#index"
  resources :proposals do
    resources :bookings, only: [:index, :new, :create]
  end
  resources :bookings, only: [:show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :booker, class_name: "User", foreign_key: "user_id"
  belongs_to :proposal
  delegate :proposer, to: :proposal
  before_create :set_room_name

  # callback ActiveRecord 
  def set_room_name
    client = Twilio::REST::Client.new(ENV["KEY_ID"], ENV["AUTH_TOKEN"])
    room = client.video.rooms.create(unique_name: "#{proposal.name}_#{Time.now.to_i}")
    self.url_room = room.unique_name
  end
end

app/models/primary_category.rb
class PrimaryCategory < ApplicationRecord
  has_many :secondary_categories, dependent: :destroy
  has_many :proposals, through: :secondary_categories, dependent: :destroy
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  belongs_to :proposer, class_name: "User", foreign_key: "user_id"
  belongs_to :secondary_category
  delegate :primary_category, to: :secondary_category, allow_nil: true
  has_one :booking, dependent: :destroy
  has_many :slots, dependent: :destroy
  # Pour simple_form #new
  attr_accessor :dates, :start_slot, :end_slot
end

app/models/secondary_category.rb
class SecondaryCategory < ApplicationRecord
  belongs_to :primary_category
  has_many :proposals,  dependent: :destroy
end

app/models/slot.rb
class Slot < ApplicationRecord
  belongs_to :proposal
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :proposals, dependent: :destroy
  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # index.html.erb
  def index
    @bookings = policy_scope(Booking).order(created_at: :desc)
  end

  def new
    @booking = Booking.new
    authorize @booking
    @proposal = Proposal.find(params[:proposal_id])
    @slots = @proposal.slots
  end

  def create
    @booking = Booking.new
    @booking.booker = current_user
    @booking.proposal = Proposal.find(params[:proposal_id])
    @booking.start_time = params[:booking][:start_time]
    authorize @booking
    if @booking.save!
      flash[:notice] = "Booking done !"
      redirect_to dashboards_path(resa: true)
    else
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
    @token = generate_token(@booking)
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    redirect_to dashboards_path(resa: true)
  end

  private



  def generate_token(booking)
    # Create an Access Token
    token = Twilio::JWT::AccessToken.new ENV['ACCOUNT_SID'], ENV['KEY_ID'], ENV['AUTH_TOKEN'], [],
        ttl: 14400,
        identity: current_user.email
    # Grant access to Video
    grant = Twilio::JWT::AccessToken::VideoGrant.new
    grant.room = booking.url_room
    token.add_grant grant
    # Serialize the token as a JWT
    token.to_jwt
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @bookings = policy_scope(Booking).order(created_at: :desc)
    # @proposals = policy_scope(Proposal).order(created_at: :desc)
    @bookings = current_user.bookings
    @proposals = current_user.proposals
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home]

  def home
    @categories = PrimaryCategory.all
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :find_proposal, only: [:destroy, :update, :show, :edit]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @booking = Booking.new
    @proposals = policy_scope(Proposal).preload(:slots).order(created_at: :desc)
    if params[:cat]
      @proposals = @proposals.select { |proposal| proposal.primary_category.id == params[:cat].to_i }
    end
    @categories = PrimaryCategory.all
  end

  def show
  end

  def new
    @proposal = Proposal.new
    @categories = PrimaryCategory.all
    authorize @proposal
  end

  def create
    @proposal = Proposal.new(proposal_params)
    @proposal.secondary_category = SecondaryCategory.find(params[:proposal][:secondary_category])
    @proposal.proposer = current_user
    authorize @proposal
    if @proposal.save!
      create_slots(@proposal)
      # 
      redirect_to dashboards_path(newprop: true)
    else
      render 'new'
    end
  end

  def update
    authorize @proposal
    if @proposal.update(proposal_params)
      redirect_to root_path
    else
      redirect_to dashboards_path(newprop: true)
    end

  end

  def destroy
    authorize @proposal
    @proposal.destroy
    redirect_to dashboards_path(newprop: true)
  end


  private

  def proposal_params
    params.require(:proposal).permit(:name, :description, :end_time, :dates, :start_slot, :end_slot)
  end

  def find_proposal
    @proposal = Proposal.find(params[:id])
  end

  def create_slots(proposal)
    # recup les dates sous forme de string
    all_dates = proposal_params[:dates].split(',')
    sslot = proposal_params[:start_slot].split(':').first.to_i
    eslot = proposal_params[:end_slot].split(':').first.to_i
    eslot == sslot ? range_slot = (sslot..sslot+1) : range_slot = (sslot..eslot-1 )
    
    all_dates.each do |date|
        range_slot.each do |slot|
          Slot.create!(start_time: DateTime.parse("#{date} #{slot}"), proposal: proposal)
        end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/bookings/index.html.erb
<h1>Vos bookings</h1>

<ul>
  <% @bookings.each do |booking| %>
  <li><%= booking.proposal.name %></li>
  <li><%= booking.proposal.primary_category.name %></li>
  <li><%= booking.proposal.secondary_category.name %></li>
  <br>
  <% end %>
</ul>

app/views/bookings/new.html.erb
<h1>Vos bookings</h1>

<%= simple_form_for [@proposal, @booking] do |f| %>
  <%= f.association :proposal, selected: @proposal %>
  <%= f.submit "Submit", class: "btn btn-cta" %>
<% end %>

app/views/bookings/show.html.erb
<div class="title-wrapper">
  <div class="container">
    <h1 class="title">Votre binôme online</h1>
  </div>
</div>

<div class="container">
  <div 
    class="twilio-video" 
    data-sid="<%= ENV["ACCOUNT_SID"] %>" 
    data-room="<%= @booking.url_room %>" 
    data-token="<%= @token %>"
    >

    <div class="row justify-content-between">
      <div class="col-7">
        <div class="participant">
        </div>
      </div>
      <div class="col-4">
        <div class="remote-media-div text-center">
          <video id="userVideo" autoplay muted="true" ></video>
          <div>
            <button id='leave-btn' class='btn btn-primary mt-3'> 
              Quittez
            </button>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-7">
      <p class="text-center">
        <%= @booking.booker == current_user ? @booking.proposal.proposer.email : @booking.booker.email %>
      </p>
      </div>
    </div>
    <%= link_to '', root_path, class: 'd-none root-link', data: {turbolinks: false}  %>

  </div>
</div>

app/views/dashboards/index.html.erb
<div class="title-wrapper">
  <div class="container">
    <h1 class="title">Mon activité</h1>
  </div>
</div>

<!-- <div class="container"> -->

<!-- </div> -->

<div class="container">
  <ul class="nav nav-pills mb-3" id="myTab" role="tablist">
    <li class="nav-item">
      <a class="nav-link <%= 'active' if params[:resa] %>" id="home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Vos réservations de coups de pouce</a>
    </li>
    <li class="nav-item">
      <a class="nav-link <%= 'active' if params[:newprop] %>" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">Vos propositions de coups de pouce</a>
    </li>
  </ul>

  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade <%= ' show active' if params[:resa] %>" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
      <div class="row">
        <% @bookings.each do |booking| %>
          <div class="col-3 m-4">
            <div class="card-dashboard-bookings" style="background-image: url('<%= image_path booking.proposal.secondary_category.image %>')">
              <div class="card-info-bookings">
                <!-- <div class="card-header d-flex justify-content-between align-items-center"> -->
                   <div class="update-delete">
                    <%= link_to booking_path(booking), method: :delete, data:{ confirm: 'Etes vous sûr de vouloir supprimer votre réservation?' } do %>
                      <i class="fas fa-trash delete-booking icon-grey"></i>
                    <% end %>
                  </div>
                  <div class="card-index-name">
                    <%= booking.proposal.name%>
                  </div>
                <!-- </div> -->
                <div class="card-dashboard-secondary-category">
                  <p>
                    <%= booking.proposal.secondary_category.name%>
                  </p>
                </div>
                <div class="card-dashboard-infos">
                  <p id="date-time"> <i class="far fa-clock icon-grey"></i><%= booking.start_time.strftime("%d %b à %R") %>
                  <p><i class="far fa-user-circle icon-grey"></i><%= booking.proposer.email %></p>
                </div>

                <%= link_to "Votre visio", booking_path(booking), class: "btn btn-index-card btn-primary " %>

              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="tab-pane fade <%= ' show active' if params[:newprop] %>" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
      <div class="row">
        <% @proposals.each do |proposal| %>

          <div class="col-3 m-4">
            <div class="card-dashboard-bookings" style="background-image: url('<%= image_path proposal.secondary_category.image %>')">
              <div class="card-info-bookings">
                <div class="update-delete">
                  <% if policy(proposal).edit? %>
                    <%= link_to edit_proposal_path(proposal), data:{ confirm: 'Etes vous sûr de vouloir modifier votre coup de pouce?' } do %>
                      <i class="fas fa-pen icon-grey"></i>
                    <% end %>
                  <% end %>
                  <% if policy(proposal).destroy? %>
                     <%= link_to proposal_path(proposal), method: :delete, data:{ confirm: 'Etes vous sûr de vouloir supprimer votre coup de pouce?' }  do %>
                        <i class="fas fa-trash icon-grey "></i>
                      <% end %>
                  <% end %>
                </div>
                <div class="card-index-name">
                  <%= proposal.name%>
                </div>
                <div class="card-dashboard-secondary-category">
                  <p>
                    <%= proposal.secondary_category.name%>
                  </p>
                </div>
                <div class="card-dashboard-infos">
                  <p id="date-time"> <i class="far fa-clock icon-grey"></i><%= proposal.slots.first.start_time.strftime("%d %b à %R")%>
                </div>

                  <% if proposal.booking.present? %>
                    <%= link_to "Votre visio", booking_path(proposal.booking), class: "btn btn-index-card btn-primary btn-dashboard-proposal" %>
                  <% end %>

              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="www.lesbinomes.online" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <%= favicon_link_tag asset_path('twocolors.png') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%# defer: true --> chargement du JS en fin de BODY pour meilleur UX %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

  </head>

  <body id="<%= controller.controller_name %>-<%= controller.action_name %>" >
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

     <div class="content-wrapper">
      <%= yield %>
    </div>

     <%= render 'shared/footer' %>
     <script src="https://media.twiliocdn.com/sdk/js/video/v1/twilio-video.min.js"></script>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">

   <div class="container">

      <div class="banner-content">
        <h1>Les Binômes</h1>
        <p>Rester solidaire <br> en temps de distanciation sociale</p>
        <a class="btn btn-primary" href="/proposals">Découvrir nos coups de pouce</a>
      </div>

  </div>

</div>

<div class="container">

  <div class="home_text">
    La distanciation sociale ne devrait pas être un frein à <strong>l'entraide</strong>. <br>
    Vous avez besoin d'un <strong>coup de pouce</strong>? <br>
    <strong>Tout peut se faire à distance</strong>!
  </div>

  <div class="home_text">
    <% @categories.each do |category| %>
      <%=  link_to proposals_path(:cat => category.id) do %>
        <div class="card-primary-category" style="background-image: url('<%= image_path category.image %>')">
          <div class="category-name">
            <p><%= category.name %></p>
          </div>
        </div>
     <% end %>
    <% end %>
  </div>
  <div class="cta">
    <a class="btn btn-primary" href="/proposals">Découvrir nos coups de pouce</a>
  </div>
</div>

app/views/proposals/_modal.html.erb
<div class="modal fade" id="modalCenter<%= proposal.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalCenterTitle"><%= proposal.name%></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">

        Prochaine disponibilité : <strong> <%= proposal.slots.first.start_time.strftime("%d %b à %R") %> </strong><br>
        Si ce créneau vous convient, réservez-le ! <br><br>
        Sinon jettez un oeil aux autres créneaux disponibles ici : <br><br>

        <%
          slots_by_date = proposal.slots.group_by do |slot|
            slot.start_time.to_date
          end
        %>

        <div class="calendar_toggle_input">
          <div class="calendar">
            <% slots_by_date.first(3).each do |date, slots| %>
              <div class="container_day">
                <div class="date">
                  <%= date.strftime("%d %b") %>
                </div>
                <div class="container_slots">
                  <% slots.each do |slot| %>
                    <div class="slot">
                      <%=slot.start_time.strftime("%R")%>
                      <div class="d-none" id="true_date"><%= slot.start_time %></div>
                    </div>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
          <br><br>
          Un lien de <strong>visioconférence</strong> vous sera envoyé dans la foulée.<br><br>
          <strong>Bon coup de pouce!</strong>

          <%= simple_form_for [proposal, booking], html: { id: "new_booking-#{proposal.id}" } do |c| %>
            <%= c.input :start_time, as: :string, label: false, input_html: { value: proposal.slots.first.start_time, class: 'd-none new_booking_start_time', id: "input_new_booking-#{proposal.id}" } %>
            <%= c.button :submit, 'Valider', class: 'btn btn-primary' %>
          <% end %>

        </div>

      </div>



    </div>
  </div>
</div>

app/views/proposals/edit.html.erb
<div class="title-wrapper" id="title-custom">
  <div class="container">
    <h1 class="title">Faites votre proposition de coup de pouce!</h1>
  </div>
</div>

app/views/proposals/index.html.erb
<div class="title-wrapper">
  <div class="container">
    <h1 class="title">Trouvez votre coup de pouce!</h1>
  </div>
</div>

<div class="container">

  <div class="text-left position-relative">
    <% @categories.each do |cat|  %>
      <%= link_to cat.name, proposals_path(:cat => cat.id), class: "btn btn-primary #{params[:cat].to_i == cat.id ? "active" : ""}" %>
    <% end %>

    <%= link_to proposals_path, class: "cross" do %>
      <i class="fas fa-times-circle"></i><br>
    <% end %>
  </div>

  <div class="row">
    <% @proposals.each do |proposal| %>
      <div class="col-4 my-4">
        <div class="card-index" style="background-image: url('<%= image_path proposal.secondary_category.image %>')">
          <div class="card-info">
            <div class="card-index-name">
              <%= proposal.name%>
            </div>
            <div class="card-index-secondary-category">
              <p>
              <%= proposal.secondary_category.name%>
              </p>
            </div>
            <div class="card-index-description">
             <%= proposal.description%>
            </div>
            <a class="button btn-index-card" data-toggle="modal" data-target="#modalCenter<%= proposal.id %>" href="/proposals">Disponibilités</a>
          </div>
        </div>
      </div>
      <%= render 'modal', proposal: proposal, booking: @booking %>
    <% end %>
  </div>
</div>

app/views/proposals/new.html.erb
<div class="title-wrapper" id="title-custom">
  <div class="container">
    <h1 class="title">Faites votre proposition de coup de pouce!</h1>
  </div>
</div>

<div class="image_form">
  <div class = "container col-4 margin-top">
    <% if policy(Proposal).create? %>


      <%= simple_form_for @proposal do |c| %>
        <%= c.input :name, placeholder: "Cuisiner des lasagnes", label: "Titre"%>
        <%= c.input :primary_category, as: :radio_buttons, collection: @categories.pluck(:name), wrapper: :vertical_collection_inline, label: "Thématique principale" %>

        <%= simple_fields_for :secondary_options do |f|  %>
          <div class="d-none secondary-input" id="soutien-scolaire">
            <%= f.input :secondary, as: :radio_buttons, collection: @categories.first.secondary_categories, wrapper: :vertical_collection_inline, label: "Précisez l'activité" %>
          </div>
          <div class="d-none secondary-input" id="moment-loisir">
            <%= f.input :secondary, as: :radio_buttons, collection: @categories.second.secondary_categories, wrapper: :vertical_collection_inline, label: "Précisez l'activité" %>
          </div>
          <div class="d-none secondary-input" id="conseils">
            <%= f.input :secondary, as: :radio_buttons, collection: @categories.third.secondary_categories, wrapper: :vertical_collection_inline, label: "Précisez l'activité" %>
          </div>
        <% end %>

        <div class="d-none">
          <%= c.input :secondary_category %>
        </div>

        <%= c.input :dates, input_html: { class: "datepicker" }, label: "Jours de disponibilités" %>
        <%= c.input :start_slot, input_html: { class: "timepicker"}, label: "Heure de début"  %>
        <%= c.input :end_slot, input_html: { class: "timepicker-end"}, label: "Heure de fin"  %>
        <%= c.input :description, as: :text, placeholder: "Pendant cette heure, je vous propose de cuisiner la recette de lasage de ma grand mère ... " %>
        <%= c.button :submit, "Validez", class: 'btn btn-primary' %>

      <% end %>
    <% end %>
  </div>
</div>

app/views/proposals/show.html.erb
<%= @proposal.name  %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i></i>Contactez-nous</a>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "twocolors.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>

        <li class="nav-item">
          <%= link_to "Devenir binôme", new_proposal_path, class: "btn btn-primary", id:"btn-binome" %>
        </li>
        <li>
          <%= link_to "Mon activité", dashboards_path(resa: true), class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "default-avatar.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>